/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import gestionnairedemission.Competence;
import gestionnairedemission.Employe;
import gestionnairedemission.Mission;
import java.util.ArrayList;

/**
 *
 * @author Maxence
 */
public class MenuPrincipal extends javax.swing.JFrame {

    public static ArrayList<Employe> listE;
    public static ArrayList<Competence> listC;
    public static ArrayList<Mission> listM;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelBtnGestions = new javax.swing.JPanel();
        jBtnGestionEmp = new javax.swing.JButton();
        jBtnGestionComp = new javax.swing.JButton();
        jBtnGestionMiss = new javax.swing.JButton();
        menuPrincipal = new javax.swing.JMenuBar();
        jMenuPrincipal = new javax.swing.JMenu();
        jMenuPrincpalItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 29)); // NOI18N
        jLabel1.setText("Gestion des compétences du personnel");

        jBtnGestionEmp.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jBtnGestionEmp.setText("Gestion du Personnel");
        jBtnGestionEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGestionEmpActionPerformed(evt);
            }
        });

        jBtnGestionComp.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jBtnGestionComp.setText("Gestion des Compétences");
        jBtnGestionComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGestionCompActionPerformed(evt);
            }
        });

        jBtnGestionMiss.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jBtnGestionMiss.setText("Gestion des Missions");
        jBtnGestionMiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGestionMissActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtnGestionsLayout = new javax.swing.GroupLayout(jPanelBtnGestions);
        jPanelBtnGestions.setLayout(jPanelBtnGestionsLayout);
        jPanelBtnGestionsLayout.setHorizontalGroup(
            jPanelBtnGestionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBtnGestionsLayout.createSequentialGroup()
                .addComponent(jBtnGestionEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnGestionComp, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnGestionMiss, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBtnGestionsLayout.setVerticalGroup(
            jPanelBtnGestionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnGestionMiss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnGestionComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnGestionEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );

        jMenuPrincipal.setText("Application");

        jMenuPrincpalItem1.setText("Fermer");
        jMenuPrincpalItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPrincpalItem1ActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(jMenuPrincpalItem1);

        menuPrincipal.add(jMenuPrincipal);
        jMenuPrincipal.getAccessibleContext().setAccessibleParent(jMenuPrincipal);

        setJMenuBar(menuPrincipal);
        menuPrincipal.getAccessibleContext().setAccessibleName("menuPrincipal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBtnGestions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelBtnGestions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuPrincpalItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPrincpalItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuPrincpalItem1ActionPerformed

    private void jBtnGestionEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGestionEmpActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        MenuPersonnel mp = new MenuPersonnel();
        mp.setLocationRelativeTo(this);
        mp.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jBtnGestionEmpActionPerformed

    private void jBtnGestionCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGestionCompActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        MenuCompetence mc = new MenuCompetence();
        mc.setLocationRelativeTo(this);
        mc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnGestionCompActionPerformed

    private void jBtnGestionMissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGestionMissActionPerformed
        // TODO add your handling code here:
        //his.dispose();
        MenuMissionGeneral mmg = new MenuMissionGeneral();
        mmg.setLocationRelativeTo(this);
        mmg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnGestionMissActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGestionComp;
    private javax.swing.JButton jBtnGestionEmp;
    private javax.swing.JButton jBtnGestionMiss;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuPrincipal;
    private javax.swing.JMenuItem jMenuPrincpalItem1;
    private javax.swing.JPanel jPanelBtnGestions;
    private javax.swing.JMenuBar menuPrincipal;
    // End of variables declaration//GEN-END:variables
}
